Функциональность основного сервиса
leliaOff/java-explore-with-me-plus pull request #22
Opened 2024-10-02 07:10 UTC by leliaOff

2024-10-03 12:37 UTC, mikita95 requested changes
Все сделано просто отлично :) Оставил лишь небольшие рекомендации

2024-10-03 12:37 UTC, mikita95 commented on ewm/src/main/resources/schema.sql
> +    category_id BIGINT NOT NULL CONSTRAINT events_categories_id_fk references categories,
Можно было бы создать индексы на колонки, по которым часто выполняются запросы, так было бы эффективнее

2024-10-03 12:54 UTC, leliaOff commented on ewm/src/main/resources/schema.sql
> +    category_id BIGINT NOT NULL CONSTRAINT events_categories_id_fk references categories,
добавили

2024-10-04 06:24 UTC, mikita95 approved these changes
Все сделано просто отлично :) Можно мержить пул-реквест

2024-10-04 06:54 UTC, merged