Тесты
leliaOff/java-explore-with-me-plus pull request #29
Opened 2024-10-05 10:59 UTC by leliaOff

2024-10-05 16:53 UTC, mikita95 requested changes
Все сделано отлично :) Оставил лишь пару рекомендаций

2024-10-05 16:53 UTC, mikita95 commented on ewm/src/main/java/ru/practicum/ewm/services/EventCommentService.java
> +        PageRequest pageRequest = PageRequest.of(from / size, size, Sort.by(Sort.Direction.ASC, "created"));
Можно было бы вынести в утилитный класс создание страницы, так можно избежать дублирования

2024-10-05 16:53 UTC, mikita95 commented on ewm/src/main/java/ru/practicum/ewm/dto/eventComment/CreateCommentRequest.java
> +import org.hibernate.validator.constraints.Length;
Валидация hibernate здесь не очень подходит, ведь это фреймворк orm

2024-10-07 06:45 UTC, leliaOff commented on ewm/src/main/java/ru/practicum/ewm/services/EventCommentService.java
> +        PageRequest pageRequest = PageRequest.of(from / size, size, Sort.by(Sort.Direction.ASC, "created"));
Все замечания устранены

2024-10-07 16:49 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-10-08 05:17 UTC, merged